import sys

def update_build_env(file_path):
    with open(file_path, 'r') as file:
        lines = file.readlines()

    # Replace 'buildEnv = True' with 'buildEnv = False'
    updated_lines = [line.replace('buildEnv = True', 'buildEnv = False') for line in lines]

    with open(file_path, 'w') as file:
        file.writelines(updated_lines)

if __name__ == "__main__":
    # Pass the file path of the script generated by nbconvert
    update_build_env(sys.argv[1])
