'''
Author:     Matthew Ogden
Created:    10 May 2019
Altered:    24 Sep 2019
Purpose:    This program is the main function that prepares galaxy models, 
                runs them through the JSPAM software, and creates particle files
'''

from sys import (
    argv,
    exit
)

from os import (
    path,
    system,
    getcwd,
    mkdir,
    chdir
)

from re import (
    compile,
    match
)

from zipfile import (
    ZipFile
)

# Global/Input Variables

printAll = True

basicRun = ""  # Set with the required flag -basicRun in new_readArg
if path.isfile("./Simulator/bin/basic_run"):
    basicRun = path.abspath("./Simulator/bin/basic_run")

runDir = ''  # Set in new_readArg
nPart = 0
maxN = 1e6  # Arbitrary limit in case of typo, can be changed if needed

compressFiles = True
overWrite = False


# SE_TODO: Work with this function for main
# Variables are checked to exist in new_readArg function, and sets exitEarly as needed
def simulator_v2(argList):
    # Takes path to info.txt file and returns that file as a list of strings
    def readInfoFile(f):
        if not path.exists(f):
            print("No info.txt found: " + f)
            return []
        file = open(f, 'r')
        res = file.read()
        file.close()
        return list(filter(None, res.split("\n")))

    # Takes list of strings that is the info.txt (As generated by readInfoFile) in question and extracts the model_data
    # information, and returns that
    def getModelData(l):
        if len(l) == 0:
            print("Empty info.txt")
            return

        r = compile(r'^model_data\s(.*)')
        for line in l:
            m = match(r, line)
            if m:
                return m.group(1)

        return ""

    endEarly = new_readArg(argList)  # Checks that things exist, and sets endEarly accordingly
    # Exit program with error
    if endEarly:
        print('Exiting...\n')
        exit(-1)

    # Read info.txt and get model data located in runDir
    md = getModelData(readInfoFile(runDir + "info.txt"))

    if md == "":
        print("Error reading model data from info.txt")
        exit(-1)

    # Double check that the particle_files exists, it should have been made by the pipeline
    if not path.isdir(runDir + "particle_files/"):
        mkdir(runDir + "particle_files/")

    # SE_TODO: Check 'particle_files' folder if particles of nPart size have already been made 
    # Ignore if overWrite is true

    # Move active directory into 'particle_files'.
    chdir(runDir + "particle_files/")

    # Call JSPAM!
    runBasicRun(nPart, mData)

    # SE_TODO: Check if particle files were created.  Should end with .000 and .101
    # SE_TODO: Rename both files as nPart_pts.000 and nPart_pts.101 (Ex. 1000_pts.000)
    # SE_TODO: Zip both files up in 1 zip file named nPart_pts.zip
    # SE_TODO: Delete .000 and .101 if they remain


def movePartFiles(uID, oDir):
    # Check if particle files were created
    fileNames = ['a_%d.000' % uID, 'a_%d.101' % uID]

    if not (path.isfile(fileNames[0]) and path.isfile(fileNames[1])):
        print('###  WARNING  ###')
        print("Particle files not found, exiting...")
        exit(-1)

    # Create directory if it doesn't exist
    if not path.isdir(oDir):
        try:
            if printAll:
                print('Creating directory %s' % oDir)
            mkdir(oDir)
        except Exception as e:
            print("Failed to create new directory: " + e)
            exit(-1)
    # End create dir

    # Zip files if requested
    if compressFiles:
        try:
            if printAll:
                print('Zipping files')

            #r1 = ZipFile("a_" + uID + "_000.zip", mode='w').write("a_" + uID + "_000")
            #r2 = ZipFile("a_" + uID + "_001.zip", mode='w').write("a_" + uID + "_001")

            zipCmd1 = 'zip a_%d_000.zip a_%d.000' % (uID, uID)
            zipCmd2 = 'zip a_%d_101.zip a_%d.101' % (uID, uID)

            #system(zipCmd1)
            #system(zipCmd2)

            if printAll:
                print('Moving files to %s' % oDir)

            if pName == '':
                mvCmd = 'mv a_%d_*.zip %s' % (uID, oDir)
                #system(mvCmd)
            else:
                mv1Cmd = 'mv a_%d_000.zip %s' % (uID, oDir + pName + '_000.zip')
                mv2Cmd = 'mv a_%d_101.zip %s' % (uID, oDir + pName + '_101.zip')
                #system(mv1Cmd)
                #system(mv2Cmd)

            rmCmd = 'rm a_%d.*' % uID
            #system(rmCmd)

        except:
            print('Failed zipping and moving')

    else:

        # Move particle files to output
        try:
            mvCmd = 'mv a_%d* %s' % (uID, oDir)
            #system(mvCmd)

        except:
            print('###  WARNING  ###')
            print('Could not move spam particle files... ', fileNames)
            return False

    return True


# movePartFiles


def runBasicRun(nPart, data):
    global basicRun

    sysCmd = '%s -m %d -n1 %d -n2 %d %s' % (basicRun, 0, nPart, nPart, data)

    if printAll:
        print('Running command: ', sysCmd)

    try:
        retVal = system(sysCmd)  # Consider implementing a way to check return val from spam code

        if printAll:
            print('Command Complete')
        return True

    except Exception as e:
        print("Failed running command due to: " + e)
        return False


# End runBasicRun


def new_readArg(argList):
    # Global input arguments
    global runDir, nPart, overWrite, basicRun

    # Loop through command line arguments
    for i, arg in enumerate(argList):

        # Ignore argument unless it has '-' specifier
        if arg[0] != '-':
            continue

        # Turns out path.abspath doesn't understand ~
        elif arg == '-runDir':
            runDir = argList[i + 1]
            if runDir[0] == '~':
                runDir = path.expanduser(runDir)
            else:
                runDir = path.abspath(runDir)

            if not runDir[-1] == '/':
                runDir += '/'

        elif arg == '-nPart':
            nPart = argList[i + 1]

        elif arg == '-overWrite':
            overWrite = True

        elif arg == '-basicRun':
            basicRun = argList[i + 1]
            if basicRun[0] == '~':
                basicRun = path.expanduser(basicRun)
            else:
                basicRun = path.abspath(basicRun)

    # Check validity of commandline arguments
    endEarly = False

    # Check if run Dir exists or if not given one
    if not path.isdir(runDir):
        if runDir == '':
            print("ERROR: Please specify path to run directory.")
            print("\t$: python simulator_v2.py -runDir /path/to/runDir ...")
        else:
            print("ERROR: Path to run directory not found: '%s'" % runDir)
        endEarly = True
    # End check runDir

    # Check if basicRun exists
    if not path.isfile(basicRun):
        print("ERROR: Can't find basic_run.")
        print("\tbasic_run location: %s" % basicRun)
        print("\tcurrent location: %s" % getcwd())
        print("\t$: python simulator_v2.py -basicRun /path/basic_run ...")
        endEarly = True

    # Check if number of particles was specified
    if nPart == 0:
        print("ERROR: Please specify number of particles per galaxy.")
        print("\t$: python simulator_v2.py -nPart 1000 ...")
        endEarly = True

    # Check if input particles was an integer
    try:
        nPart = int(nPart)
    except:
        print("ERROR: -nPart is not an integer: '%s'" % nPart)
        nPart = 0
        endEarly = True

    return endEarly


# End new_readArg


# Execute everything after declaring functions
print('')
if __name__ == "__main__":
    argList = argv
    simulator_v2(argList)
print('')
